---
name: Run vm manager jenkins job


on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: "**"
  pull_request_review:
    types: [submitted]
    branches: "**"

env:
    PR_EVENT: ${{ github.event.action }}
    PR_URL: https://github.com/${{github.repository}}/pull/${{ github.event.pull_request.number }}
    PR_LABEL: ${{ github.event.label.name }}
    BUILDTOKEN: vmmanager
    JENKINS_URL: https://cbjenkins-ba.devtools.intel.com/teams-satg-aee-android-ci/generic-webhook-trigger/invoke?token=

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: echo vars
        run: 
            echo "The PR_EVENT is ${{ env.PR.EVENT }}"
            echo "The PR_URL is ${{ env.PR_URL }}"
            echo "The TOKEN is ${{ PR_LABEL }}"
            
      - name: Trigger Jenkins Build with PR Information
        run: |- 
               curl --location --request POST  ${{ JENKINS_URL }}${{ BUILDTOKEN }}   \
                      --header 'Content-Type: application/json' \
                      --data-raw '{
                        "action": ${{ PR_EVENT }} ,
                        "pull_request": {
                          "html_url": ${{ PR_URL }}
                        },
                        "label": {
                          "name": ${{ PR_LABEL }}
                        }                        
                      }'
