---
name: Run vm manager jenkins job


on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: "**"
  pull_request_review:
    types: [submitted]
    branches: "**"

env:
    EVENT_CONTEXT: ${{ toJSON(github.event) }}
    BUILDTOKEN: test_vmmanager
    JENKINS_URL: https://cbjenkins-ba.devtools.intel.com/teams-satg-aee-android-ci/generic-webhook-trigger/invoke?token=

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: converting object to json
        run: echo ${{ env.EVENT_CONTEXT }}
        
