---
name: Run vm manager jenkins job


on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: "**"
  pull_request_review:
    types: [submitted]
    branches: "**"

env:
    PR_URL: https://github.com/${{github.repository}}/pull/${{ github.event.pull_request.number }}
    BUILDTOKEN: test_vmmanager
    JENKINS_URL: https://cbjenkins-ba.devtools.intel.com/teams-satg-aee-android-ci/generic-webhook-trigger/invoke?token=

jobs:
  Build:
    runs-on: self-hosted
    steps:            
      - name: Trigger Jenkins Build with PR Information
        run: |- 
               curl --location --request POST  ${{ env.JENKINS_URL }}${{ env.BUILDTOKEN }}   \
                      --header 'Content-Type: application/json' \
                      --data-raw '{
                        "raw": ${{ github.event }} ,
                        },                        
                      }'
