on:
  issues:
    types: [closed]
    branches: "**"
    
env:
    EVENT_CONTEXT: ${{ toJSON(github.event) }}
    BUILDTOKEN: test_vmmanagermerge
    JENKINS_URL: https://cbjenkins-ba.devtools.intel.com/teams-satg-aee-android-ci/generic-webhook-trigger/invoke?token=

jobs:
  if_closed:
    runs-on: self-hosted
    steps:
    - run: |
        echo The PR was merged
    - name: converting object to json
      env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: |
          echo "$EVENT_CONTEXT"
    - name: Triggering Jenkins job
      run: |
        echo The PR was merged

